apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30000   # Specify the desired NodePort value here
  type: NodePort       # Use NodePort type for the service
